import type { DocumentType, TemplateMetadata } from "@/types/models";

export const templateCatalog: Record<DocumentType, TemplateMetadata> = {
  invoice: {
    templateId: "invoice-praxis-v2",
    templateVersion: "v1",
    docType: "invoice",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      shipperNameAddress: "Form Configuration!B1:D2",
      applicant: "Contract-SI-LC!K31",
      contractRef: "Contract!C5",
      contractDate: "Contract!C7",
      paymentTerm: "Contract-SI-LC!K16",
      deliveryTerm: "Contract-SI-LC!K17",
      destination: "Contract-SI-LC!K20",
      portOfLoading: "Contract-SI-LC!K24",
      description: "Contract-SI-LC!K28",
      quantityLb: "Contract!D28",
      netWeightKg: "Contract!D26",
      grossWeightKg: "Contract!H26",
      noOfBags: "Contract-SI-LC!K25",
      totalPrice: "Contract-SI-LC!K12",
      bagMarking: "Contract-SI-LC!K27",
    },
  },
  packing_list: {
    templateId: "packing-praxis-v2",
    templateVersion: "v1",
    docType: "packing_list",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      shipperNameAddress: "Form Configuration!B1:D2",
      applicant: "Contract-SI-LC!K31",
      consignee: "Contract-SI-LC!K29",
      contractRef: "Contract!C5",
      deliveryTerm: "Contract-SI-LC!K17",
      portOfLoading: "Contract-SI-LC!K24",
      destination: "Contract-SI-LC!K20",
      hsCode: "Form Configuration!D16",
      billOfLading: "Bookings!B43",
      vessel: "Bookings!C6",
      voyageNo: "Bookings!C7",
      description: "Contract-SI-LC!K28",
      grossWeightMt: "Contract!H30",
      netWeightMt: "Contract!D30",
      bagsPerContainer: "Contract-SI-LC!K25 / Contract!D34",
      processingStation: "Processing!D6",
      processingAddress: "Processing!D9",
    },
  },
  shipping_instructions: {
    templateId: "si-praxis-v2",
    templateVersion: "v1",
    docType: "shipping_instructions",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      shipperNameAddress: "Form Configuration!B1:D2",
      consignee: "Contract-SI-LC!K29",
      notify: "Contract-SI-LC!K30",
      secondNotify: "Contract-SI-LC!K32",
      productDescription:
        "SI!E18 (Contract-SI-LC!K13 + Contract-SI-LC!K14 + Contract-SI-LC!F37 + Contract!C5)",
      hsCode: "Form Configuration!D16",
      quantityExpression: "SI!E20 (Contract!D18, Contract!D34)",
      grossWeightKg: "Contract!H26",
      netWeightKg: "Contract!D26",
      certRange: "Contract!F54",
      containerCount: "Contract!D34",
      portOfLoading: "Contract-SI-LC!K24",
      destination: "Contract-SI-LC!K20",
      bookingNumber: "Bookings!C4",
    },
  },
};
