import type { DocumentType, TemplateMetadata } from "@/types/models";

export const templateCatalog: Record<DocumentType, TemplateMetadata> = {
  invoice: {
    templateId: "invoice-praxis-v2",
    templateVersion: "v1",
    docType: "invoice",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      shipperNameAddress: "Form Configuration!B1:D2",
      applicant: "Contract-SI-LC!K31",
      contractRef: "Contract!C5",
      contractDate: "Contract!C7",
      paymentTerm: "Contract-SI-LC!K16",
      deliveryTerm: "Contract-SI-LC!K17",
      destination: "Contract-SI-LC!K20",
      portOfLoading: "Contract-SI-LC!K24",
      description: "Contract-SI-LC!K28",
      quantityLb: "Contract!D28",
      netWeightKg: "Contract!D26",
      grossWeightKg: "Contract!H26",
      noOfBags: "Contract-SI-LC!K25",
      totalPrice: "Contract-SI-LC!K12",
      bagMarking: "Contract-SI-LC!K27",
    },
  },
  packing_list: {
    templateId: "packing-praxis-v2",
    templateVersion: "v1",
    docType: "packing_list",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      shipperNameAddress: "Form Configuration!B1:D2",
      applicant: "Contract-SI-LC!K31",
      consignee: "Contract-SI-LC!K29",
      contractRef: "Contract!C5",
      deliveryTerm: "Contract-SI-LC!K17",
      portOfLoading: "Contract-SI-LC!K24",
      destination: "Contract-SI-LC!K20",
      hsCode: "Form Configuration!D16",
      billOfLading: "Bookings!B43",
      vessel: "Bookings!C6",
      voyageNo: "Bookings!C7",
      description: "Contract-SI-LC!K28",
      grossWeightMt: "Contract!H30",
      netWeightMt: "Contract!D30",
      bagsPerContainer: "Contract-SI-LC!K25 / Contract!D34",
      processingStation: "Processing!D6",
      processingAddress: "Processing!D9",
    },
  },
  shipping_instructions: {
    templateId: "si-praxis-v2",
    templateVersion: "v1",
    docType: "shipping_instructions",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      shipperNameAddress: "Form Configuration!B1:D2",
      consignee: "Contract-SI-LC!K29",
      notify: "Contract-SI-LC!K30",
      secondNotify: "Contract-SI-LC!K32",
      productDescription:
        "SI!E18 (Contract-SI-LC!K13 + Contract-SI-LC!K14 + Contract-SI-LC!F37 + Contract!C5)",
      hsCode: "Form Configuration!D16",
      quantityExpression: "SI!E20 (Contract!D18, Contract!D34)",
      grossWeightKg: "Contract!H26",
      netWeightKg: "Contract!D26",
      certRange: "Contract!F54",
      containerCount: "Contract!D34",
      portOfLoading: "Contract-SI-LC!K24",
      destination: "Contract-SI-LC!K20",
      bookingNumber: "Bookings!C4",
    },
  },
  quality_certificate: {
    templateId: "certificate-quality-praxis-v2",
    templateVersion: "v1",
    docType: "quality_certificate",
    effectiveFrom: "2026-04-23",
    fieldMap: {
      titleStatement: "Certificate of Quality!B9 (Contract-SI-LC!K28)",
      modeOfTransportation: "Certificate of Quality!C11 (Bookings!C5,C6,C7,B43)",
      moistureContent: "Certificate of Quality!C12 (Processing!D4)",
      shipper: "Certificate of Quality!C13 (Form Configuration!B1:D2)",
      notify: "Certificate of Quality!C14 (Contract-SI-LC!K30)",
      secondNotify: "Certificate of Quality!C15 (Contract-SI-LC!K32)",
      description: "Certificate of Quality!C16 (Contract-SI-LC!K28)",
      origin: "Certificate of Quality!C17 (Form Configuration!K7)",
      quality: "Certificate of Quality!C18 (Contract-SI-LC!K7)",
      icoNo: "Certificate of Quality!C19 (Form Configuration!A12 + Contract!F54)",
      certNo: "Certificate of Quality!C20 (Contract!F54)",
      netWeight: "Certificate of Quality!C21 (Contract!D26)",
      grossWeight: "Certificate of Quality!C22 (Contract!H26)",
      quantityLb: "Certificate of Quality!C23 (Contract!D28)",
      from: "Certificate of Quality!C24 (Contract-SI-LC!K24)",
      to: "Certificate of Quality!C25 (Contract-SI-LC!K20)",
      containerTable: "Certificate of Quality!B28:D37 (Staffing!G22:H31 + bags/container)",
      signatoryCompany: "Certificate of Quality!C39 (Form Configuration!B1)",
    },
  },
  weight_certificate: {
    templateId: "certificate-weight-praxis-v2",
    templateVersion: "v1",
    docType: "weight_certificate",
    effectiveFrom: "2026-04-23",
    fieldMap: {
      shipper: "Certificate of Weight!C9 (Form Configuration!B1:D2)",
      notify: "Certificate of Weight!C10 (Contract-SI-LC!K30)",
      secondNotify: "Certificate of Weight!C11 (Contract-SI-LC!K32)",
      description: "Certificate of Weight!C12 (Contract-SI-LC!K28)",
      netWeight: "Certificate of Weight!C13 (Contract!D26 + KG)",
      grossWeight: "Certificate of Weight!C14 (Contract!H26 + KG)",
      packagesInBags: "Certificate of Weight!C15 (Contract-SI-LC!F35)",
      origin: "Certificate of Weight!C16 (Form Configuration!K7)",
      quality: "Certificate of Weight!C17 (Contract-SI-LC!K7)",
      icoNo: "Certificate of Weight!C18 (Form Configuration!A12 + Contract!F54)",
      certNo: "Certificate of Weight!C19 (Contract!F54)",
      from: "Certificate of Weight!C20 (Contract-SI-LC!K24)",
      to: "Certificate of Weight!C21 (Contract-SI-LC!K20)",
      containerTable: "Certificate of Weight!C25:I34 (Staffing!G/H + bag/container + per-container net/gross)",
      totalNetWeight: "Certificate of Weight!H35 (SUM H25:H34 + KGS)",
      totalGrossWeight: "Certificate of Weight!I35 (SUM I25:I34 + KGS)",
    },
  },
};
