import type { DocumentType, TemplateMetadata } from "@/types/models";

export const templateCatalog: Record<DocumentType, TemplateMetadata> = {
  invoice: {
    templateId: "invoice-praxis-v2",
    templateVersion: "v1",
    docType: "invoice",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      shipperNameAddress: "Form Configuration!B1:D2",
      applicant: "Contract-SI-LC!K31",
      contractRef: "Contract!C5",
      contractDate: "Contract!C7",
      paymentTerm: "Contract-SI-LC!K16",
      deliveryTerm: "Contract-SI-LC!K17",
      destination: "Contract-SI-LC!K20",
      portOfLoading: "Contract-SI-LC!K24",
      description: "Contract-SI-LC!K28",
      quantityLb: "Contract!D28",
      netWeightKg: "Contract!D26",
      grossWeightKg: "Contract!H26",
      noOfBags: "Contract-SI-LC!K25",
      totalPrice: "Contract-SI-LC!K12",
      bagMarking: "Contract-SI-LC!K27",
    },
  },
  packing_list: {
    templateId: "packing-praxis-v2",
    templateVersion: "v1",
    docType: "packing_list",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      salesContractRef: "Packing List(ICC)!O8 = Contract!C5",
      salesContractDate: "Packing List(ICC)!O9 = Contract!C7",
      exporterBeneficiarySeller: "Packing List(ICC)!C11 = CONCAT(Form Configuration!B1:D1, Form Configuration!B2:D2)",
      bankPermitNumber: "Packing List(ICC)!I11 = Bank & LC!H5",
      billOfLadingNumber: "Packing List(ICC)!I13 = Bookings!B43",
      applicantNotify: "Packing List(ICC)!C14 = Contract-SI-LC!K30",
      shippingLine: "Packing List(ICC)!M14 = Bookings!C5",
      vesselName: "Packing List(ICC)!Q14 = Bookings!C6",
      voyageNo: "Packing List(ICC)!O15 = Bookings!C7",
      consignee: "Packing List(ICC)!C17 = Contract-SI-LC!K29",
      descriptionOfGoods: "Packing List(ICC)!C20 = Contract-SI-LC!K28",
      hsCode: "Packing List(ICC)!D21 = Form Configuration!D16",
      containerRows: "Packing List(ICC)!C23:E32 = Staffing!G22:H31",
      packageRows: "Packing List(ICC)!G23:K32 = Contract-SI-LC!K25 / Contract!D34",
      netWeightRows: "Packing List(ICC)!L23:O32 = Contract!D26 / Contract!D34",
      grossWeightRows: "Packing List(ICC)!P23:S32 = Contract!H26 / Contract!D34",
      countryOfOrigin: "Packing List(ICC)!E34 = Form Configuration!K7",
      portOfLoading: "Packing List(ICC)!E35 = Contract-SI-LC!K24",
      portOfDischarge: "Packing List(ICC)!E36 = Contract-SI-LC!K20",
      finalDestination: "Packing List(ICC)!E37 = Contract-SI-LC!K20",
      deliveryTradeTerm: "Packing List(ICC)!E38 = Contract-SI-LC!K17",
      termMethodOfPayment: "Packing List(ICC)!C42 = Contract-SI-LC!K16",
      packagingMarkingLabel: "Packing List(ICC)!C44 = Contract-SI-LC!F35",
      totalNetWeightMt: "Packing List(ICC)!D46 = Contract!D30",
      totalGrossWeightMt: "Packing List(ICC)!F46 = Contract!H30",
      packingPlace: "Packing List(ICC)!E48 = Processing!D6",
      packingAddress: "Packing List(ICC)!E49 = Processing!D9",
      fullMarking: "Packing List(ICC)!E51 = Contract-SI-LC!K27",
    },
  },
  shipping_instructions: {
    templateId: "si-praxis-v2",
    templateVersion: "v1",
    docType: "shipping_instructions",
    effectiveFrom: "2026-03-03",
    fieldMap: {
      shipperNameAddress: "Form Configuration!B1:D2",
      consignee: "Contract-SI-LC!K29",
      notify: "Contract-SI-LC!K30",
      secondNotify: "Contract-SI-LC!K32",
      productDescription:
        "SI!E18 (Contract-SI-LC!K13 + Contract-SI-LC!K14 + Contract-SI-LC!F37 + Contract!C5)",
      hsCode: "Form Configuration!D16",
      quantityExpression: "SI!E20 (Contract!D18, Contract!D34)",
      grossWeightKg: "Contract!H26",
      netWeightKg: "Contract!D26",
      certRange: "Contract!F54",
      containerCount: "Contract!D34",
      portOfLoading: "Contract-SI-LC!K24",
      destination: "Contract-SI-LC!K20",
      bookingNumber: "Bookings!C4",
    },
  },
  quality_certificate: {
    templateId: "certificate-quality-praxis-v2",
    templateVersion: "v1",
    docType: "quality_certificate",
    effectiveFrom: "2026-04-23",
    fieldMap: {
      titleStatement: "Certificate of Quality!B9 (Contract-SI-LC!K28)",
      modeOfTransportation: "Certificate of Quality!C11 (Bookings!C5,C6,C7,B43)",
      moistureContent: "Certificate of Quality!C12 (Processing!D4)",
      shipper: "Certificate of Quality!C13 (Form Configuration!B1:D2)",
      notify: "Certificate of Quality!C14 (Contract-SI-LC!K30)",
      secondNotify: "Certificate of Quality!C15 (Contract-SI-LC!K32)",
      description: "Certificate of Quality!C16 (Contract-SI-LC!K28)",
      origin: "Certificate of Quality!C17 (Form Configuration!K7)",
      quality: "Certificate of Quality!C18 (Contract-SI-LC!K7)",
      icoNo: "Certificate of Quality!C19 (Form Configuration!A12 + Contract!F54)",
      certNo: "Certificate of Quality!C20 (Contract!F54)",
      netWeight: "Certificate of Quality!C21 (Contract!D26)",
      grossWeight: "Certificate of Quality!C22 (Contract!H26)",
      quantityLb: "Certificate of Quality!C23 (Contract!D28)",
      from: "Certificate of Quality!C24 (Contract-SI-LC!K24)",
      to: "Certificate of Quality!C25 (Contract-SI-LC!K20)",
      containerTable: "Certificate of Quality!B28:D37 (Staffing!G22:H31 + bags/container)",
      signatoryCompany: "Certificate of Quality!C39 (Form Configuration!B1)",
    },
  },
  weight_certificate: {
    templateId: "certificate-weight-praxis-v2",
    templateVersion: "v1",
    docType: "weight_certificate",
    effectiveFrom: "2026-04-23",
    fieldMap: {
      shipper: "Certificate of Weight!C9 (Form Configuration!B1:D2)",
      notify: "Certificate of Weight!C10 (Contract-SI-LC!K30)",
      secondNotify: "Certificate of Weight!C11 (Contract-SI-LC!K32)",
      description: "Certificate of Weight!C12 (Contract-SI-LC!K28)",
      netWeight: "Certificate of Weight!C13 (Contract!D26 + KG)",
      grossWeight: "Certificate of Weight!C14 (Contract!H26 + KG)",
      packagesInBags: "Certificate of Weight!C15 (Contract-SI-LC!F35)",
      origin: "Certificate of Weight!C16 (Form Configuration!K7)",
      quality: "Certificate of Weight!C17 (Contract-SI-LC!K7)",
      icoNo: "Certificate of Weight!C18 (Form Configuration!A12 + Contract!F54)",
      certNo: "Certificate of Weight!C19 (Contract!F54)",
      from: "Certificate of Weight!C20 (Contract-SI-LC!K24)",
      to: "Certificate of Weight!C21 (Contract-SI-LC!K20)",
      containerTable: "Certificate of Weight!C25:I34 (Staffing!G/H + bag/container + per-container net/gross)",
      totalNetWeight: "Certificate of Weight!H35 (SUM H25:H34 + KGS)",
      totalGrossWeight: "Certificate of Weight!I35 (SUM I25:I34 + KGS)",
    },
  },
  way_bill: {
    templateId: "way-bill-praxis-v2",
    templateVersion: "v1",
    docType: "way_bill",
    effectiveFrom: "2026-04-23",
    fieldMap: {
      to: "WAY BILL!C11 (Form Configuration!E19)",
      toLocationPhone: "WAY BILL!C12 (Form Configuration!E21 + E20)",
      driverSelector: "WAY BILL!C16 (Data validation from Staffing!AI6:AI10)",
      truckNo: "WAY BILL!C14 (Staffing row by MATCH driver)",
      trailerNo: "WAY BILL!C15 (Staffing next row by MATCH driver + 1)",
      driverPhoneNo: "WAY BILL!C17 (Staffing row col 4)",
      licenseNo: "WAY BILL!C18 (Staffing row col 5)",
      finalDestination: "WAY BILL!C19 (Contract-SI-LC!K24)",
      driverDeclaration: "WAY BILL!B21 (CONCATENATE using driver name)",
      detailOfGoods: "WAY BILL!C28 (Seller + origin + grade)",
      icoNo: "WAY BILL!D29 (ICO prefix + cert, single/dual row aware)",
      certNo: "WAY BILL!D30 (Cert number single/dual row aware)",
      noOfBag: "WAY BILL!D31 (Contract bags/container with pair multiplier)",
      grossWeight: "WAY BILL!D32 (Contract gross/container with pair multiplier)",
      netWeight: "WAY BILL!D33 (Contract net/container with pair multiplier)",
      containerSealTruck: "WAY BILL!E36,H36 (Staffing row col 6/7)",
      containerSealTrailer: "WAY BILL!E38,H38 (Staffing row+1 col 6/7)",
      amharicDeclaration:
        "WAY BILL!C39 (ከላይ የተጠቀሱትን ህግና ደንቦች አንብቤና ተረድቼ ለማንኛውም ችግር ሀላፊነት ለመውሰድ በፊርማየ አረጋግጣለሁ፡ ፡)",
    },
  },
  ico_certificate: {
    templateId: "ico-certificate-praxis-v2",
    templateVersion: "v1",
    docType: "ico_certificate",
    effectiveFrom: "2026-05-10",
    fieldMap: {
      exporterConsignor: "ICO!B2",
      notifyAddress: "Contract-SI-LC!K30",
      internalReferenceNo: "Contract!C5",
      countryCode: "Form Configuration!A12 (prefix segment 1)",
      portCode: "Form Configuration!A12 (prefix segment 2)",
      serialNo: "Contract!F54",
      producingCountry: "ICO!D6 / Contract-SI-LC!K13",
      countryOfDestination: "ICO!B7 / Contract-SI-LC!K20",
      dateOfExport: "ICO!D7",
      countryOfTransShipment: "Company Configuration transitorLocation",
      nameOfCarrier: "ICO!C9 = Bookings!C5 + C6 + C7",
      icoIdentificationMark: "ICO!B12",
      shippedInFlags: "ICO!B13,D10,F12,B15",
      netWeightOfShipment: "ICO!D12 = Contract!D26",
      unitOfWeight: "ICO!F12/F13 (kg/lb marker)",
      descriptionOfCoffee: "ICO!C14",
      processingMethod: "ICO!B15",
      signDatePlace: "ICO!B20/D20",
    },
  },
  bill_of_lading: {
    templateId: "msc-bill-of-lading-v1",
    templateVersion: "v1",
    docType: "bill_of_lading",
    effectiveFrom: "2026-06-07",
    fieldMap: {
      shipper: "Company Configuration sellerName + sellerAddress",
      consignee: "Resolved final consignee",
      notifyParty: "Resolved final notify",
      notify2: "Bill of Lading override notify2",
      notify3: "Bill of Lading override notify3",
      vesselVoyage: "Bookings vesselName + voyageNo",
      portOfLoading: "Shipping/LC final port of loading",
      portOfDischarge: "Shipping/LC final destination",
      placeOfReceipt: "Bill of Lading override placeOfReceipt",
      placeOfDelivery: "Bill of Lading override placeOfDelivery",
      cargoMarks: "Bill of Lading override cargoMarksText",
      goodsDescription: "Bill of Lading override descriptionOverride or derived contract description",
      grossCargoWeight: "Derived gross contract weight",
      measurement: "Bill of Lading override measurement",
      freightAndCharges: "Bill of Lading override freightAndChargesText",
    },
  },
};
