import type { TemplateSection } from "@/domain/template-layout";

export const WAY_BILL_DEFAULT_SECTIONS: TemplateSection[] = [
  {
    id: "header_meta",
    label: "Header + Meta",
    description: "Way bill title, date, and reference number.",
    x: 0,
    y: 0,
    w: 12,
    h: 6,
    minH: 6,
    cells: [
      { id: "wb_title", label: "WAY BILL", x: 0, y: 0, w: 12, h: 2 },
      { id: "wb_date", label: "Date", x: 0, y: 2, w: 6, h: 2 },
      { id: "wb_ref", label: "Ref No", x: 6, y: 2, w: 6, h: 2 },
    ],
  },
  {
    id: "transport",
    label: "Transport Details",
    description: "Transitor, truck/trailer, driver, and destination.",
    x: 0,
    y: 0,
    w: 12,
    h: 16,
    minH: 16,
    cells: [
      { id: "wb_to", label: "To", x: 0, y: 0, w: 12, h: 2 },
      { id: "wb_to_contact", label: "To Contact", x: 0, y: 2, w: 12, h: 2 },
      { id: "wb_truck", label: "Truck No", x: 0, y: 4, w: 12, h: 2 },
      { id: "wb_trailer", label: "Trailer No", x: 0, y: 6, w: 12, h: 2 },
      { id: "wb_driver", label: "Driver Name", x: 0, y: 8, w: 12, h: 2 },
      { id: "wb_driver_phone", label: "Driver Phone No", x: 0, y: 10, w: 12, h: 2 },
      { id: "wb_license", label: "License No", x: 0, y: 12, w: 12, h: 2 },
      { id: "wb_destination", label: "Final Destination", x: 0, y: 14, w: 12, h: 2 },
    ],
  },
  {
    id: "declaration",
    label: "Driver Declaration",
    description: "Driver declaration heading and text.",
    x: 0,
    y: 0,
    w: 12,
    h: 8,
    minH: 8,
    cells: [
      { id: "wb_decl_title", label: "Driver's Declaration", x: 0, y: 0, w: 12, h: 2 },
      { id: "wb_driver_decl", label: "Driver Declaration", x: 0, y: 2, w: 12, h: 6 },
    ],
  },
  {
    id: "conditions",
    label: "Terms and Conditions",
    description: "Way bill terms and conditions block.",
    x: 0,
    y: 0,
    w: 12,
    h: 8,
    minH: 8,
    cells: [
      { id: "wb_terms_intro", label: "Terms Intro", x: 0, y: 0, w: 12, h: 2 },
      { id: "wb_condition_1", label: "Condition 1", x: 0, y: 2, w: 12, h: 2 },
      { id: "wb_condition_2", label: "Condition 2", x: 0, y: 4, w: 12, h: 2 },
      { id: "wb_condition_3", label: "Condition 3", x: 0, y: 6, w: 12, h: 2 },
    ],
  },
  {
    id: "goods",
    label: "Goods",
    description: "Detail of goods and weights.",
    x: 0,
    y: 0,
    w: 12,
    h: 14,
    minH: 14,
    cells: [
      { id: "wb_goods_hdr", label: "Detail of Goods", x: 0, y: 0, w: 12, h: 2 },
      { id: "wb_goods_desc", label: "Detail of Goods", x: 0, y: 2, w: 12, h: 2 },
      { id: "wb_ico", label: "ICO No", x: 0, y: 4, w: 12, h: 2 },
      { id: "wb_cert", label: "Cert No", x: 0, y: 6, w: 12, h: 2 },
      { id: "wb_bags", label: "No of Bag", x: 0, y: 8, w: 12, h: 2 },
      { id: "wb_gross", label: "Gross Weight", x: 0, y: 10, w: 12, h: 2 },
      { id: "wb_net", label: "Net Weight", x: 0, y: 12, w: 12, h: 2 },
    ],
  },
  {
    id: "transport_charge",
    label: "Transport Charge",
    description: "Way bill transport charge line.",
    x: 0,
    y: 0,
    w: 12,
    h: 4,
    minH: 4,
    cells: [
      { id: "wb_transport_label", label: "Transport Charge Label", x: 0, y: 0, w: 6, h: 2 },
      { id: "wb_transport_per_quantal", label: "Transport Charge Per Quantal", x: 6, y: 0, w: 3, h: 2 },
      { id: "wb_transport_total", label: "Transport Charge Total", x: 9, y: 0, w: 3, h: 2 },
    ],
  },
  {
    id: "containers",
    label: "Containers",
    description: "Container and seal numbers.",
    x: 0,
    y: 0,
    w: 12,
    h: 6,
    minH: 6,
    cells: [
      { id: "wb_container_hdr_container", label: "Container No", x: 0, y: 0, w: 6, h: 2 },
      { id: "wb_container_hdr_seal", label: "Seal No", x: 6, y: 0, w: 6, h: 2 },
      { id: "wb_container_1", label: "Container No 1", x: 0, y: 2, w: 6, h: 2 },
      { id: "wb_seal_1", label: "Seal No 1", x: 6, y: 2, w: 6, h: 2 },
      { id: "wb_container_2", label: "Container No 2", x: 0, y: 4, w: 6, h: 2 },
      { id: "wb_seal_2", label: "Seal No 2", x: 6, y: 4, w: 6, h: 2 },
    ],
  },
  {
    id: "amharic",
    label: "Amharic Declaration",
    description: "Amharic declaration text block.",
    x: 0,
    y: 0,
    w: 12,
    h: 4,
    minH: 4,
    cells: [
      { id: "wb_amharic", label: "Amharic Declaration", x: 0, y: 0, w: 12, h: 4 },
    ],
  },
  {
    id: "footer",
    label: "Footer Signatures",
    description: "Driver name, signature, and date lines.",
    x: 0,
    y: 0,
    w: 12,
    h: 6,
    minH: 6,
    cells: [
      { id: "wb_footer_driver_name", label: "Driver Name Row", x: 0, y: 0, w: 12, h: 2 },
      { id: "wb_footer_signature", label: "Signature Row", x: 0, y: 2, w: 12, h: 2 },
      { id: "wb_footer_date", label: "Date Row", x: 0, y: 4, w: 12, h: 2 },
    ],
  },
  {
    id: "document_id",
    label: "Document ID",
    description: "Footer document ID line.",
    x: 0,
    y: 0,
    w: 12,
    h: 4,
    minH: 4,
    showDocumentId: false,
    cells: [],
  },
];
